version: '3'
services:
  php_apsi:
    build: ./php
    image: php:latest
    container_name: php_apsi
    hostname: "php"
    volumes:
      - ./apsi_project:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - mysql_apsi

  mysql_apsi:
    image: mariadb:10.2
    container_name: mysql_apsi
    restart: unless-stopped
    tty: true
    ports:
      - "33333:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: djony
      MYSQL_PASSWORD: Djony
      MYSQL_ROOT_PASSWORD: Djony
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql  
    read_only: false

  nginx_apsi:
    build: ./nginx
    image: nginx:latest
    container_name: nginx_apsi
    hostname: "nginx"
    ports:
      - "105:80"
    volumes:
      - ./apsi_project:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_apsi
